config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#home'
  resources :products do 
    resources :reviews 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  
  has_many :reviews, dependent: :destroy
  validates :name, presence: :true
  validates :cost, presence: :true
  validates :country_of_origin, presence: :true
  
  before_save(:titleize_product)
  
  scope :three_most_recent, -> { order(created_at: :desc).limit(3) }
  
  scope :usa, -> { where(country_of_origin: "United States of America") }

  scope :most_reviewed, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
  )}

  private
    def titleize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product 
  validates :author, presence: true
  validates :content_body, presence: true
  validates :rating, presence: true
  validates_length_of :content_body, maximum: 250
  validates_length_of :content_body, minimum: 50
  validates_numericality_of :rating, only_integer: true
  validates_numericality_of :rating, less_than_or_equal_to: 5
  validates_numericality_of :rating, greater_than_or_equal_to: 1

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :edit, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def index
    @products = Product.all
    render :index
  end

  def home 
    @products = Product.all 
    render :home 
  end
  
  def new 
    @product = Product.new
    render :new
  end

  def create 
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product has been added. Thank you for your contribution"
      redirect_to products_path
    else 
      render :new
    end
  end

  def edit 
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update 
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "You have successfully updated this product. We are so proud of you"
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy 
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "You took the initiative to delete this inferior product. Your ancestors are certainly smiling down on you"
    redirect_to products_path
  end


  private 
    def product_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :only => [ :edit, :update, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new 
    render :new
  end

  def create 
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save 
      flash[:notice] = "Thank you for your review. It means so much" 
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show 
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update 
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Wow, what a brilliant update you've made here."
      redirect_to product_path(@review.product)
    else
      @product = Product.find(params[:product_id])
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Discretion is the better part of valor. I appreciate yours"
    redirect_to product_path(@review.product)
  end




  private 
    def review_params
      params.require(:review).permit(:author, :content_body, :rating)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %> 
  <h3>Please Fix The Following Errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %> 

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.submit  %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mario Has Food</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "layouts/product_form" %>

<h4><%= link_to "Return Home", root_path %></h4>

app/views/products/home.html.erb
<h1>WELCOME TO MARIO</h1>
<p>Hey hey hey, We are Mario and We are here to sell you food!</p>


<p>We are a family who have been serving this community since like three weeks ago. A long history of standing with the local community</p>

<p>At Mario, we believe in three things. Healthy food, healthy community, healthy communication, and that the moon is fake</p>

<p>Wait..whoops, that was four things. We at Mario believe in four things</p>

<% if current_user %>
<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %> 
<%= link_to 'Sign up', new_user_registration_path %>
<%= link_to 'Sign in', new_user_session_path %>
<% end %>

<% if @products.any? %>

<h4>What is new at Mario?</h4>
<ol>
  <% @products.three_most_recent.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ol>

<h4>USA! USA! USA! See what fine american products we have</h4>
<ul>
  <% @products.usa.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>

  <h4>See our most reviewed item!</h4>
  <ul>
    <% @products.most_reviewed.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% end %> 

<h4>Full Product List</h4>
<p><%= link_to "Look at all products", products_path %></p>

app/views/products/index.html.erb
<h1>Products</h1>
<% if @products.any? %>
<ul> 
  <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %>
  <% end %>
  <% else %> 
    <p>We have got nothin for sale yet<p>
  <% end %>

  <p><%= link_to "Add a new Product", new_product_path %></p>
  <br>
  <h4><%= link_to "Return Home", root_path %></h4>
  

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "layouts/product_form" %>

<h4><%= link_to "Return Home", root_path %></h4>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3>$<%= @product.cost %></h3>
<h3>Country of Origin: <%= @product.country_of_origin %></h3>

<% if @product.reviews.any? %>
  <h4>Here are the people who have reviewed this item:</h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.author, product_review_path(@product, review) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews yet!</p>
<% end %>

<p><%= link_to "Write a review!", new_product_review_path(@product) %></p>

<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete", product_path(@product), :data => {:confirm => "Are you sure? Once it is gone it is gone", :method => "delete" } %></p>
<p><%= link_to "Return to product list", products_path %></p>

<h4><%= link_to "Return Home", root_path %></h4>

app/views/reviews/edit.html.erb
<h1>Edit a review!</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>Add a review!</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>Reviewer: <%= @review.author %></h1>
<h2>Product: <%= @product.name %></h2>
<h2>Rating: <%= @review.rating %></h2>
<h3><%= @review.content_body %></h3>

<p><%= link_to "Edit", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete", product_review_path(@product, @review), :data => {:confirm => "Are you sure? Once it is gone it is gone", :method => "delete" } %></p>
<p><%= link_to "Return to product", products_path(@product) %></p>